---
# PwnKit mitigation
#
# This playbook will check if Polkit is installed on host and disable SUID-bit permission for pkexec binary on a Linux host.
#
# More information:
# - CVE-2021-4034:
#   https://blog.qualys.com/vulnerabilities-threat-research/2022/01/25/pwnkit-local-privilege-escalation-vulnerability-discovered-in-polkits-pkexec-cve-2021-4034
#
# Anthony SANCHEZ <sanchez.antho@free.fr> - 29-01-2022
# MIT license

- name: PwnKit mitigation
  hosts: all
  become: true

  tasks:
    - name: Loading the OS specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family | lower }}.yml"
      tags: os-variables

    - name: Check if Polkit is installed and remove SUID-bit permission on pkexec binary.
      block:
        - name: Gather the package facts
          ansible.builtin.package_facts:

        - name: Show message when polkit is installed
          ansible.builtin.debug:
            msg: >
              Package '{{ ansible_facts.packages[polkit_package][0].name }}' in
              version {{ ansible_facts.packages[polkit_package][0].version }} is installed.
          when:
            - "'polkit' in ansible_facts.packages"

        - name: Show message when polkit isn't installed
          ansible.builtin.debug:
            msg: "polkit isn't installed"
          when:
            - "'polkit' not in ansible_facts.packages"

        - name: Check if pkexec binary is present
          ansible.builtin.stat:
            path: "{{ pkexec_path }}"
          register: polkit_pkexec
          when:
            - "'polkit' in ansible_facts.packages"

        - name: Remove SUID-bit on pkexec binary when present
          ansible.builtin.file:
            path: "{{ pkexec_path }}"
            mode: "{{ pkexec_mode }}"
          when:
            - polkit_pkexec.stat.exists
      rescue:
        - name: Error(s) caught
          debug:
            msg: "An error was occurred during apply PwnKit mitigation fix: {{ ansible_failed_task.name }}"
      tags: apply-mitigation
...
